{{- if .Values.controllerManager.webhook.enabled }}
{{- $existingWebhooks := dict }}
{{- if not (eq .Values.global.certManagementMode "manual") }}
  {{- $obj := lookup "admissionregistration.k8s.io/v1" "ValidatingWebhookConfiguration" "" "kthena-controller-manager-validating-webhook" }}
  {{- if $obj }}
    {{- range $obj.webhooks }}
      {{- $_ := set $existingWebhooks .name .clientConfig.caBundle }}
    {{- end }}
  {{- end }}
{{- end }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name:  kthena-controller-manager-validating-webhook
  labels:
    app.kubernetes.io/component: webhook
    {{- include "kthena.labels" . | nindent 4 }}
  {{- if eq .Values.global.certManagementMode "cert-manager" }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kthena-webhook-cert
  {{- end }}
webhooks:
  - name: validate-modelbooster.volcano.sh
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: kthena-controller-manager-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate/modelbooster"
        port: 443
      {{- if or (eq .Values.global.certManagementMode "auto") (eq .Values.global.certManagementMode "cert-manager") }}
      caBundle: {{ get $existingWebhooks "validate-modelbooster.volcano.sh" | default "" }}
      {{- else }}
      caBundle: {{ required "A caBundle is required for the kthena-controller-manager validating webhook when certManagementMode is set to 'manual' (global.webhook.caBundle)" .Values.global.webhook.caBundle | quote }}
      {{- end }}
    rules:
      - apiGroups: [ "workload.serving.volcano.sh" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "modelboosters" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
  - name: validate-autoscalingpolicy.volcano.sh
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: kthena-controller-manager-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate/autoscalingpolicy"
        port: 443
      {{- if or (eq .Values.global.certManagementMode "auto") (eq .Values.global.certManagementMode "cert-manager") }}
      caBundle: {{ get $existingWebhooks "validate-autoscalingpolicy.volcano.sh" | default "" }}
      {{- else }}
      caBundle: {{ required "A caBundle is required for the kthena-controller-manager validating webhook when certManagementMode is set to 'manual' (global.webhook.caBundle)" .Values.global.webhook.caBundle | quote }}
      {{- end }}
    rules:
      - apiGroups: [ "workload.serving.volcano.sh" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "autoscalingpolicies" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
  - name: validate-autoscalingpolicybinding.volcano.sh
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: kthena-controller-manager-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate/autoscalingpolicybinding"
        port: 443
      {{- if or (eq .Values.global.certManagementMode "auto") (eq .Values.global.certManagementMode "cert-manager") }}
      caBundle: {{ get $existingWebhooks "validate-autoscalingpolicybinding.volcano.sh" | default "" }}
      {{- else }}
      caBundle: {{ required "A caBundle is required for the kthena-controller-manager validating webhook when certManagementMode is set to 'manual' (global.webhook.caBundle)" .Values.global.webhook.caBundle | quote }}
      {{- end }}
    rules:
      - apiGroups: [ "workload.serving.volcano.sh" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "autoscalingpolicybindings" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
  - name: validate-workload-ai-v1alpha1-modelserving.volcano.sh
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: kthena-controller-manager-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate-workload-ai-v1alpha1-modelserving"
        port: 443
      {{- if or (eq .Values.global.certManagementMode "auto") (eq .Values.global.certManagementMode "cert-manager") }}
      caBundle: {{ get $existingWebhooks "validate-workload-ai-v1alpha1-modelserving.volcano.sh" | default "" }}
      {{- else }}
      caBundle: {{ required "A caBundle is required for the kthena-controller-manager validating webhook when certManagementMode is set to 'manual' (global.webhook.caBundle)" .Values.global.webhook.caBundle | quote }}
      {{- end }}
    rules:
      - apiGroups: [ "workload.serving.volcano.sh" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "modelservings" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
{{- end }}