apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelserving-controller-ranktable
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["workload.kthena.io"]
    resources: ["modelservings"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["workload.kthena.io"]
    resources: ["modelservings/status"]
    verbs: ["update", "patch"]
